### ISSUE TITLE
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 

### ISSUE THREAD

**Issue by kazumaxneo** [arun96/sketching#1]
Hi,

I tried but unknown errror occured. 
What is the problem?
I use nanopore reads (reads/ONT.fq) from bacterial genomes and their genomes (genome/ref.fasta).

$ java -cp screen_java:jars/\* Main -g genome/ -r reads -o ./ -rl 10000 -re 0.05 -tm 10
Running experiment with matched genomes and reads - accuracy will be computed and output.
Generating MinHash-based Screen, using default hash function.
manual_polished.fasta 5750
Screening Reads...
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at ReadScreener.<init>(ReadScreener.java:113)
	at Main.run(Main.java:95)
	at Main.main(Main.java:59)

my java is
$ java --version
openjdk 11.0.1 2018-10-16 LTS
OpenJDK Runtime Environment Zulu11.2+3 (build 11.0.1+13-LTS)
OpenJDK 64-Bit Server VM Zulu11.2+3 (build 11.0.1+13-LTS, mixed mode)

**Comment by arun96** [comment]
Hi! I'm super sorry about the extremely late reply to this - I must have totally missed the Github notification about this, and I was super busy with a few other things.

Looking at your error message, the error seems to have been encountered when trying to access the reads directory and find the files containing the read sets. The list of read sets is identified in Settings.java (starting from line 623), and from your error, it looks like no read sets were found inside the provided reads folder (and therefore no read sets were in array, resulting in a length of 0).

Having run a simple test here (one reference in genome/, one set of reads in reads/), I think the solution for this kind of issue would be to pass in "reads/" instead of just "reads", so that the ONT.fq file is found inside the reads folder.

Once again, I'm so sorry about taking so long to get back to this, and thank you for raising this issue. I hope you're doing well and staying safe!
